version: '3.9'

services:
  # PostgreSQL
  postgres:
    container_name: sample_postgres
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    restart: always

  # pgAdmin
  pgadmin4:
    container_name: sample_pgadmin
    image: dpage/pgadmin4:5.7
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    restart: always
